### ISSUE TITLE
Doesn't load images: Failed to load SPARQL backend

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.gnome.Photos#1]
hi, i am using linuxmint 18.2, cinnamon desktop, 64 bit machine (laptop) . I downloaded gnome photos to use it in linuxmint but i have this message:
![gnome photos](https://user-images.githubusercontent.com/29207169/32608526-390d1240-c522-11e7-8335-49c2c19c081b.png)
Is gnome photos only for gnome desktop? 
i have already xdg-desktop-portal installed

**Comment by debarshiray** [comment]
Well, it states the problem right there. You need to have a working Tracker installation for it to pick up your images. Also, bugs (like this one) that are not strictly related to the Flatpak packaging are better filed at bugzilla.gnome.org.

**Comment by Lvaskz** [comment]
OK

**Comment by Lvaskz** [comment]
hi, i have linuxmint 18.3 and i have gnome online acount installed. the photos flatpak does not synchronize with it, but the gnome photos repository from  software manager does.

**Comment by debarshiray** [comment]
> i have gnome online acount installed. the photos flatpak does
> not synchronize with it, but the gnome photos repository from
> software manager does

Let's use #2 for that.

**Comment by debarshiray** [comment]
See [bug 787029](https://bugzilla.gnome.org/show_bug.cgi?id=787029) for another take on the matter.
