### ISSUE TITLE
gnome photos.flatpak does not synchronize with gnome accounts in linux mint 18.3

### ISSUE THREAD

**Issue by Lvaskz** [flathub/org.gnome.Photos#2]
Greetings, I recently downloaded the gnome photos.flatpak. I installed that package in linuxmint 18.3 which has default support for flatpak and gnome acounts. Gnome acounts works fine on linuxmint 18.3, I can synchronize it perfectly with the gnome photos.deb package, but not with gnome photos of flatpak. A popup window appears with an error.

**Comment by Lvaskz** [comment]
I have the same issue with ubuntu 18.04

**Comment by debarshiray** [comment]
Yes, this is a known problem. See [GNOME/gnome-photos#83](https://gitlab.gnome.org/GNOME/gnome-photos/issues/83). Let's track this upstream because it requires actual code changes.
