### ISSUE TITLE
No access to removable media

### ISSUE THREAD

**Issue by jimmac** [flathub/org.gnome.Photos#7]
The removable SD card is visible as a device when I plug it, but then the import view never populates with photos to import.

**Comment by TingPing** [comment]
It only has access to the photos and download directories.

`flatpak override --user --filesystem=/the/path/to/your/card org.gnome.Photos`

**Comment by jimmac** [comment]
As much as the workaround would work for one some of us, it's a worthy goal to have import be functional.

**Comment by TingPing** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/200

**Comment by debarshiray** [comment]
Yes, SD cards, as opposed to cameras plugged in over USB via PTP or MTP, have had problems. @jimmac do you see something similar to this [screenshot](https://gitlab.gnome.org/GNOME/gnome-photos/issues/96) ?

**Comment by jimmac** [comment]
Nope, the view is completely blank.

**Comment by debarshiray** [comment]
I have upstreamed this to the [GNOME GitLab](https://gitlab.gnome.org/GNOME/gnome-photos/issues/119).
